### ISSUE TITLE
Augment model object 

### ISSUE THREAD

**Issue by gsc4** [ajkluber/inherent_structure#1]
Currently the model is created using an `.ini` file. This won't capture parts of the Hamiltonian that are added in scripts, such as disulfides or harmonic umbrellas, that need to be accounted for during minimization. 

I suggest an argument that will augment the model using local code so that any external modification can be taken into account.

**Comment by ajkluber** [comment]
[This input argument](https://github.com/ajkluber/inherent_structure/blob/master/generate.py#L155) to include a path to a python script will achieve this function. The python script should have a function called `augment_model` that takes and returns a `model` object.
